name: CI
   
on: 
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1

  build-2:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1

  build-3:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1

  build-4:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1

  build-5:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1

  build-6:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1

  build-7:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1

  build-8:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1
  build-9:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1
  build-10:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1
  build-11:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1
  build-12:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1
  build-13:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1
  build-14:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1
  build-15:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1
  build-16:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1
  build-17:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1
  build-18:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1
  build-19:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1
  build-20:
    runs-on: ubuntu-20.04
    container:
      image: docker:stable
    steps:
      - name: Run
        run: docker run -e NUMBER_OF_THREADS=16 ngthvan1612/consumer-backup:v1
